
#include <stdint.h>
#include <systemlib/param/param.h>

// DO NOT EDIT
// This file is autogenerated from parameters.xml

__BEGIN_DECLS

struct px4_parameters_t {

	const unsigned int param_count;
};

extern const struct px4_parameters_t px4_parameters;
