
#include <px4_parameters.h>

// DO NOT EDIT
// This file is autogenerated from paramaters.xml

const
#ifndef __PX4_DARWIN
__attribute__((used, section("__param")))
#endif
struct px4_parameters_t px4_parameters = {

	0
};

//extern const struct px4_parameters_t px4_parameters;

__END_DECLS

